INSERT INTO VM.APPOINTMENT_CATEGORY (ACID, CATEGORY_NAME) VALUES (1, 'Visitor');
INSERT INTO VM.APPOINTMENT_CATEGORY (ACID, CATEGORY_NAME) VALUES (2, 'Interview');
INSERT INTO VM.APPOINTMENT_CATEGORY (ACID, CATEGORY_NAME) VALUES (3, 'ABCD');
INSERT INTO VM.APPOINTMENT_CATEGORY (ACID, CATEGORY_NAME) VALUES (4, 'A');
INSERT INTO VM.APPOINTMENT_CATEGORY (ACID, CATEGORY_NAME) VALUES (5, 'B');