INSERT INTO VM.DEPT (DEPTNO, DNAME) VALUES (4, 'Security');
INSERT INTO VM.DEPT (DEPTNO, DNAME) VALUES (1, 'IT');
INSERT INTO VM.DEPT (DEPTNO, DNAME) VALUES (2, 'Engineering');
INSERT INTO VM.DEPT (DEPTNO, DNAME) VALUES (3, 'Finance');