INSERT INTO VM.EMPLOYEE_CATEGORY (CATID, CATNAME) VALUES (3, 'Constractor');
INSERT INTO VM.EMPLOYEE_CATEGORY (CATID, CATNAME) VALUES (4, 'Visitor');
INSERT INTO VM.EMPLOYEE_CATEGORY (CATID, CATNAME) VALUES (1, 'Permenant');
INSERT INTO VM.EMPLOYEE_CATEGORY (CATID, CATNAME) VALUES (2, 'Intern');